-- Releases table. Note: there is no "status" column — status is derived at
-- runtime from the completed steps and is never persisted.
CREATE TABLE releases (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)  NOT NULL,
    release_date    TIMESTAMP     NOT NULL,
    additional_info VARCHAR(5000),
    created_at      TIMESTAMP     NOT NULL,
    updated_at      TIMESTAMP     NOT NULL
);

-- Completed checklist steps, one row per (release, step). Maps to the
-- @ElementCollection on Release.completedSteps. Cascade delete so a release's
-- steps are removed with it.
CREATE TABLE release_completed_steps (
    release_id BIGINT      NOT NULL REFERENCES releases (id) ON DELETE CASCADE,
    step       VARCHAR(64) NOT NULL,
    CONSTRAINT pk_release_completed_steps PRIMARY KEY (release_id, step)
);

CREATE INDEX idx_release_completed_steps_release_id
    ON release_completed_steps (release_id);
