package com.releasecheck.service;

import com.releasecheck.dto.CreateReleaseRequest;
import com.releasecheck.dto.ReleaseResponse;
import com.releasecheck.dto.ReleaseSummaryResponse;
import com.releasecheck.dto.ToggleStepRequest;
import com.releasecheck.dto.UpdateInfoRequest;
import com.releasecheck.entity.Release;
import com.releasecheck.exception.ResourceNotFoundException;
import com.releasecheck.mapper.ReleaseMapper;
import com.releasecheck.repository.ReleaseRepository;
import java.util.List;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Business logic for managing releases.
 *
 * <p>The service sits between the controller (HTTP concerns) and the repository
 * (persistence). It owns transactions and orchestrates the repository + mapper.
 * Dependencies are injected via the constructor — generated by Lombok's
 * {@code @RequiredArgsConstructor} for the {@code final} fields — which keeps
 * the class immutable and trivially unit-testable.
 */
@Service
@RequiredArgsConstructor
@Transactional
public class ReleaseService {

    private final ReleaseRepository releaseRepository;
    private final ReleaseMapper releaseMapper;

    @Transactional(readOnly = true)
    public List<ReleaseSummaryResponse> getAllReleases() {
        return releaseRepository.findAllByOrderByReleaseDateDesc().stream()
                .map(releaseMapper::toSummary)
                .toList();
    }

    @Transactional(readOnly = true)
    public ReleaseResponse getRelease(Long id) {
        return releaseMapper.toResponse(findOrThrow(id));
    }

    public ReleaseResponse createRelease(CreateReleaseRequest request) {
        Release saved = releaseRepository.save(releaseMapper.toEntity(request));
        return releaseMapper.toResponse(saved);
    }

    public ReleaseResponse updateInfo(Long id, UpdateInfoRequest request) {
        Release release = findOrThrow(id);
        release.setAdditionalInfo(request.additionalInfo());
        // saveAndFlush forces the @PreUpdate callback so the response carries a
        // fresh updatedAt timestamp.
        return releaseMapper.toResponse(releaseRepository.saveAndFlush(release));
    }

    public ReleaseResponse toggleStep(Long id, ToggleStepRequest request) {
        Release release = findOrThrow(id);
        if (Boolean.TRUE.equals(request.completed())) {
            release.getCompletedSteps().add(request.step());
        } else {
            release.getCompletedSteps().remove(request.step());
        }
        return releaseMapper.toResponse(releaseRepository.saveAndFlush(release));
    }

    public void deleteRelease(Long id) {
        releaseRepository.delete(findOrThrow(id));
    }

    private Release findOrThrow(Long id) {
        return releaseRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Release", id));
    }
}
